

export const vpnConnect = (req,res)=>{
  res.json({
   "status":{
      "message":"success",
      "code":"200",
      "code_str":"ok",
      "extra_data":""
   },
   "data":[
      {
         "cat_id":"1",
         "cat_name":"Animal",
         "thumnail_img":"img/tinified/thumb/animal.png",
         "premium":"N",
         "rintones_count":"15",
         "updated":"2022-01-05T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/animal 20potrait.png"
      },
      {
         "cat_id":"2",
         "cat_name":"Baby ",
         "thumnail_img":"img/tinified/thumb/baby.png",
         "premium":"N",
         "rintones_count":"17",
         "updated":"2022-01-05T12:15:00Z",
         "likes":"56",
         "banner_image":"img/tinified/baby.png"
      },
      {
         "cat_id":"3",
         "cat_name":"Cartoon",
         "thumnail_img":"img/tinified/thumb/cartoon.png",
         "premium":"N",
         "rintones_count":"19",
         "updated":"2022-01-05T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/cartoon.png"
      },
      {
         "cat_id":"4",
         "cat_name":"Funny",
         "thumnail_img":"img/tinified/thumb/funny.png",
         "premium":"N",
         "rintones_count":"30",
         "updated":"2022-01-05T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/funny.png"
      },
      {
         "cat_id":"5",
         "cat_name":"Game",
         "thumnail_img":"img/tinified/thumb/game.png",
         "premium":"N",
         "rintones_count":"19",
         "updated":"2022-01-05T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/game.png"
      },
      {
         "cat_id":"6",
         "cat_name":"India",
         "thumnail_img":"img/tinified/thumb/india.png",
         "premium":"N",
         "rintones_count":"18",
         "updated":"2022-01-05T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/india.png"
      },
      {
         "cat_id":"7",
         "cat_name":"Movie",
         "thumnail_img":"img/tinified/thumb/movie.png",
         "premium":"N",
         "rintones_count":"13",
         "updated":"2022-01-05T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/movie.png"
      },
      {
         "cat_id":"8",
         "cat_name":"Nature",
         "thumnail_img":"img/tinified/thumb/nature.png",
         "premium":"N",
         "rintones_count":"21",
         "updated":"2022-01-05T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/nature.png"
      },
      {
         "cat_id":"9",
         "cat_name":"Pop",
         "thumnail_img":"img/tinified/thumb/pop.png",
         "premium":"N",
         "rintones_count":"20",
         "updated":"2022-01-05T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/pop.png"
      },
      {
         "cat_id":"10",
         "cat_name":"Classic",
         "thumnail_img":"img/tinified/thumb/classic.png",
         "premium":"N",
         "rintones_count":"20",
         "updated":"2022-01-05T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/classic.png"
      },
      {
         "cat_id":"11",
         "cat_name":"Retro",
         "thumnail_img":"img/tinified/thumb/retro.png",
         "premium":"N",
         "rintones_count":"20",
         "updated":"2022-01-05T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/retro.png"
      },
      {
         "cat_id":"13",
         "cat_name":"Blues",
         "thumnail_img":"img/tinified/thumb/Blues.png",
         "premium":"N",
         "rintones_count":"15",
         "updated":"2022-03-23T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/Blues.png"
      },
      {
         "cat_id":"15",
         "cat_name":"CuteFunny",
         "thumnail_img":"img/tinified/thumb/CuteFunny.png",
         "premium":"N",
         "rintones_count":"15",
         "updated":"2022-03-23T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/CuteFunny.png"
      },
      {
         "cat_id":"16",
         "cat_name":"Dance",
         "thumnail_img":"img/tinified/thumb/Dance.png",
         "premium":"N",
         "rintones_count":"13",
         "updated":"2022-03-23T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/Dance.png"
      },
      {
         "cat_id":"17",
         "cat_name":"Electronical",
         "thumnail_img":"img/tinified/thumb/Electronical.png",
         "premium":"N",
         "rintones_count":"15",
         "updated":"2022-03-23T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/Electronical.png"
      },
      {
         "cat_id":"19",
         "cat_name":"Jazz",
         "thumnail_img":"img/tinified/thumb/Jazz.png",
         "premium":"N",
         "rintones_count":"15",
         "updated":"2022-03-23T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/Jazz.png"
      },
      {
         "cat_id":"20",
         "cat_name":"Latin",
         "thumnail_img":"img/tinified/thumb/Latin.png",
         "premium":"N",
         "rintones_count":"15",
         "updated":"2022-03-23T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/Latin.png"
      },
      {
         "cat_id":"22",
         "cat_name":"Notification",
         "thumnail_img":"img/tinified/thumb/Notification.png",
         "premium":"N",
         "rintones_count":"15",
         "updated":"2022-03-23T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/Notification.png"
      },
      {
         "cat_id":"23",
         "cat_name":"Others",
         "thumnail_img":"img/tinified/thumb/Others.png",
         "premium":"N",
         "rintones_count":"14",
         "updated":"2022-03-23T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/Others.png"
      },
      {
         "cat_id":"24",
         "cat_name":"Rock",
         "thumnail_img":"img/tinified/thumb/Rock.png",
         "premium":"N",
         "rintones_count":"16",
         "updated":"2022-03-23T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/Rock.png"
      },
      {
         "cat_id":"26",
         "cat_name":"Christmas",
         "thumnail_img":"img/tinified/thumb/christmas.png",
         "premium":"N",
         "rintones_count":"15",
         "updated":"2022-01-13T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/christmas.png"
      },
      {
         "cat_id":"27",
         "cat_name":"default",
         "thumnail_img":"img/tinified/thumb/christmas.png",
         "premium":"N",
         "rintones_count":"15",
         "updated":"2023-06-09T12:15:00Z",
         "likes":"25",
         "banner_image":"img/tinified/christmas.png"
      },
      {
         "cat_id":"28",
         "cat_name":"Classical",
         "thumnail_img":"img/Classical/thumb/christmas.png",
         "premium":"N",
         "rintones_count":"15",
         "updated":"2023-06-09T12:15:00Z",
         "likes":"25",
         "banner_image":"img/Classical/christmas.png"
      },
      {
         "cat_id":"29",
         "cat_name":"HipHop",
         "thumnail_img":"img/HipHop/thumb/christmas.png",
         "premium":"N",
         "rintones_count":"15",
         "updated":"2023-06-09T12:15:00Z",
         "likes":"25",
         "banner_image":"img/HipHop/christmas.png"
      }
   ]
});
}

export const vpnDisconnect = (req,res)=>{
    
}